-- =====================================================================================
-- V1: Initial schema for TaskFlow
--
-- Conventions:
--   * UUID primary keys, generated by the app (BaseEntity#ensureId), not by Postgres
--   * Every tenant-owned table carries organization_id as the FIRST column after id
--   * Timestamps are timestamptz (UTC)
--   * Soft-delete via deleted_at; partial indexes exclude soft-deleted rows from hot
--     query paths
--   * created_by / updated_by are nullable to allow system writes
--
-- Index strategy:
--   * Composite indexes are ordered for the dominant query (tenant first, then sort/filter)
--   * Partial indexes (WHERE deleted_at IS NULL) keep the active-row index small and hot
--   * activity_log gets a DESC index on created_at for cheap recent-first feed reads
-- =====================================================================================

-- pgcrypto is available by default in modern PG; we don't need uuid generation server-
-- side but having gen_random_uuid() around is useful for ad-hoc inserts.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ----------------------------------------------------------------------- users
CREATE TABLE users (
    id               uuid PRIMARY KEY,
    email            varchar(255) NOT NULL UNIQUE,
    password_hash    varchar(100) NOT NULL,
    full_name        varchar(120) NOT NULL,
    avatar_url       varchar(512),
    enabled          boolean      NOT NULL DEFAULT true,
    last_login_at    timestamptz,
    created_at       timestamptz  NOT NULL,
    updated_at       timestamptz  NOT NULL,
    created_by       uuid,
    updated_by       uuid
);

CREATE INDEX idx_users_email_lower ON users (lower(email));

-- --------------------------------------------------------------- organizations
CREATE TABLE organizations (
    id               uuid PRIMARY KEY,
    name             varchar(120) NOT NULL,
    slug             varchar(64)  NOT NULL UNIQUE,
    description      varchar(1000),
    created_at       timestamptz  NOT NULL,
    updated_at       timestamptz  NOT NULL,
    created_by       uuid,
    updated_by       uuid
);

-- ---------------------------------------------------- organization_memberships
CREATE TABLE organization_memberships (
    id               uuid PRIMARY KEY,
    user_id          uuid NOT NULL,
    organization_id  uuid NOT NULL,
    role             varchar(16) NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'MEMBER')),
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id)         REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_org  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT uk_membership_user_org UNIQUE (user_id, organization_id)
);

-- "Which orgs does this user belong to?" — login path
CREATE INDEX idx_memberships_user ON organization_memberships (user_id);
-- "List all members of this org" — org settings page
CREATE INDEX idx_memberships_org  ON organization_memberships (organization_id);

-- -------------------------------------------------------------------- projects
CREATE TABLE projects (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL,
    name             varchar(120) NOT NULL,
    key              varchar(10)  NOT NULL,
    description      varchar(2000),
    deleted_at       timestamptz,
    created_at       timestamptz  NOT NULL,
    updated_at       timestamptz  NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_project_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT uk_project_org_key UNIQUE (organization_id, key)
);

-- Hot query: list active projects in an org, newest first
CREATE INDEX idx_projects_org_active ON projects (organization_id, created_at DESC)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------- boards
CREATE TABLE boards (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL,
    project_id       uuid NOT NULL,
    name             varchar(120) NOT NULL,
    description      varchar(2000),
    version          bigint NOT NULL DEFAULT 0,
    deleted_at       timestamptz,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_board_org     FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_board_project FOREIGN KEY (project_id)      REFERENCES projects(id)      ON DELETE CASCADE
);

CREATE INDEX idx_boards_project_active ON boards (project_id, created_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_boards_org ON boards (organization_id) WHERE deleted_at IS NULL;

-- -------------------------------------------------------------- board_columns
CREATE TABLE board_columns (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL,
    board_id         uuid NOT NULL,
    name             varchar(80) NOT NULL,
    position         bigint NOT NULL,
    wip_limit        integer,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_column_org   FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_column_board FOREIGN KEY (board_id)        REFERENCES boards(id)        ON DELETE CASCADE
);

-- Render board left-to-right: ORDER BY position
CREATE INDEX idx_columns_board_position ON board_columns (board_id, position);

-- ------------------------------------------------------------------------ tasks
CREATE TABLE tasks (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL,
    board_id         uuid NOT NULL,
    column_id        uuid NOT NULL,
    assignee_id      uuid,
    title            varchar(300) NOT NULL,
    description      text,
    priority         varchar(10)  NOT NULL DEFAULT 'MEDIUM'
                       CHECK (priority IN ('LOW','MEDIUM','HIGH','URGENT')),
    position         bigint NOT NULL,
    due_date         timestamptz,
    version          bigint NOT NULL DEFAULT 0,
    deleted_at       timestamptz,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_task_org      FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_board    FOREIGN KEY (board_id)        REFERENCES boards(id)        ON DELETE CASCADE,
    CONSTRAINT fk_task_column   FOREIGN KEY (column_id)       REFERENCES board_columns(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id)     REFERENCES users(id)         ON DELETE SET NULL
);

-- Covering composite for the board-render query:
--   SELECT * FROM tasks WHERE board_id = ? AND deleted_at IS NULL
--   ORDER BY column_id, position
CREATE INDEX idx_tasks_board_column_position
    ON tasks (board_id, column_id, position)
    WHERE deleted_at IS NULL;

-- "My tasks" view per assignee, newest first
CREATE INDEX idx_tasks_assignee
    ON tasks (assignee_id, updated_at DESC)
    WHERE deleted_at IS NULL AND assignee_id IS NOT NULL;

-- Tenant-scoped sweep / admin queries
CREATE INDEX idx_tasks_org_updated
    ON tasks (organization_id, updated_at DESC)
    WHERE deleted_at IS NULL;

-- --------------------------------------------------------------------- comments
CREATE TABLE comments (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL,
    task_id          uuid NOT NULL,
    author_id        uuid NOT NULL,
    body             text NOT NULL,
    deleted_at       timestamptz,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_comment_org    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_task   FOREIGN KEY (task_id)         REFERENCES tasks(id)         ON DELETE CASCADE,
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id)       REFERENCES users(id)         ON DELETE CASCADE
);

CREATE INDEX idx_comments_task_created ON comments (task_id, created_at)
    WHERE deleted_at IS NULL;

-- ------------------------------------------------------------------ invitations
CREATE TABLE invitations (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL,
    invited_by       uuid NOT NULL,
    email            varchar(255) NOT NULL,
    role             varchar(16)  NOT NULL CHECK (role IN ('ADMIN','MANAGER','MEMBER')),
    token_hash       varchar(128) NOT NULL UNIQUE,
    status           varchar(16)  NOT NULL DEFAULT 'PENDING'
                       CHECK (status IN ('PENDING','ACCEPTED','REVOKED','EXPIRED')),
    expires_at       timestamptz  NOT NULL,
    accepted_at      timestamptz,
    created_at       timestamptz  NOT NULL,
    updated_at       timestamptz  NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_inv_org  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_user FOREIGN KEY (invited_by)      REFERENCES users(id)         ON DELETE CASCADE
);

-- Pending invitations listing in org settings
CREATE INDEX idx_invitations_org_status ON invitations (organization_id, status);
-- Block duplicate pending invitations for the same email in the same org
CREATE UNIQUE INDEX uk_invitations_org_email_pending
    ON invitations (organization_id, lower(email))
    WHERE status = 'PENDING';

-- ----------------------------------------------------------------- activity_log
CREATE TABLE activity_log (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL,
    actor_id         uuid,
    activity_type    varchar(32) NOT NULL,
    board_id         uuid,
    task_id          uuid,
    project_id       uuid,
    payload          jsonb,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_activity_org   FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_actor FOREIGN KEY (actor_id)        REFERENCES users(id)         ON DELETE SET NULL
);

-- Primary feed read: org-wide newest-first
CREATE INDEX idx_activity_org_created ON activity_log (organization_id, created_at DESC);
-- Per-board feed
CREATE INDEX idx_activity_board_created ON activity_log (board_id, created_at DESC)
    WHERE board_id IS NOT NULL;
-- Per-task feed
CREATE INDEX idx_activity_task_created ON activity_log (task_id, created_at DESC)
    WHERE task_id IS NOT NULL;

-- ---------------------------------------------------------------- refresh_tokens
CREATE TABLE refresh_tokens (
    id               uuid PRIMARY KEY,
    user_id          uuid NOT NULL,
    token_hash       varchar(128) NOT NULL UNIQUE,
    session_id       uuid NOT NULL,
    expires_at       timestamptz NOT NULL,
    revoked_at       timestamptz,
    replaced_by_id   uuid,
    user_agent       varchar(255),
    ip_address       varchar(45),
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    created_by       uuid,
    updated_by       uuid,
    CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- List active tokens for a user (revocation, "log out other devices")
CREATE INDEX idx_rt_user_active ON refresh_tokens (user_id)
    WHERE revoked_at IS NULL AND replaced_by_id IS NULL;
-- Session-level revocation
CREATE INDEX idx_rt_session ON refresh_tokens (session_id);
